config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :etapas
  resources :boards
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root to: "boards#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :etapas

  validates_presence_of :nome

  before_destroy :delete_etapas_and_tasks

  private
  def delete_etapas_and_tasks
    begin
      etapas.each do |etapa|
        etapa.tasks.each do |task|
          task.destroy!
        end
        etapa.destroy!
      end
    rescue StandardError => e
      ap e
    end
  end

end

app/models/etapa.rb
class Etapa < ApplicationRecord
  belongs_to :board

  validates_presence_of :nome, :ordem

  has_many :tasks, dependent: :delete_all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :etapa

  validates_presence_of :nome, :descricao

  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, :dependent => :destroy
  has_and_belongs_to_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    session[:user_board] = @board.id
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.user = current_user

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
      @etapas = @board.etapas.order('ordem ASC') unless @board.etapas.empty?

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:nome, :descricao, :color, :user_id)
    end
end

app/controllers/etapas_controller.rb
class EtapasController < ApplicationController
  before_action :set_etapa, only: [:show, :edit, :update, :destroy]

  # GET /etapas
  # GET /etapas.json
  def index
    @etapas = Etapa.all
  end

  # GET /etapas/1
  # GET /etapas/1.json
  def show
  end

  # GET /etapas/new
  def new
    @etapa = Etapa.new
  end

  # GET /etapas/1/edit
  def edit
  end

  # POST /etapas
  # POST /etapas.json
  def create
    @etapa = Etapa.new(etapa_params)

    respond_to do |format|
      if @etapa.save
        format.html { redirect_to board_url(@etapa.board), notice: 'Etapa was successfully created.' }
        format.json { render :show, status: :created, location: @etapa }
      else
        format.html { render :new }
        format.json { render json: @etapa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etapas/1
  # PATCH/PUT /etapas/1.json
  def update
    respond_to do |format|
      if @etapa.update(etapa_params)
        format.html { redirect_to board_url(@etapa.board), notice: 'Etapa was successfully updated.' }
        format.json { render :show, status: :ok, location: @etapa }
      else
        format.html { render :edit }
        format.json { render json: @etapa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etapas/1
  # DELETE /etapas/1.json
  def destroy
    @etapa.destroy
    respond_to do |format|
      format.html { redirect_to board_url(@etapa.board), notice: 'Etapa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etapa
      @etapa = Etapa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etapa_params
      params.require(:etapa).permit(:nome, :board_id, :ordem)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_board, only: [:new, :update, :edit]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @etapa = Etapa.find(params[:etapa])
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to board_url(@task.etapa.board), notice: 'A task foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to board_url(@task.etapa.board), notice: 'A task foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: boards_path) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_board
    @board = Board.find(session[:user_board])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:nome, :descricao, :status, :etapa_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def get_etapas(task:)
    board = task.etapa.board
    result = []

    board.etapas.each do |etapa|
      result << [etapa.nome, etapa.id]
    end

    return result
  end
end

app/helpers/etapas_helper.rb
module EtapasHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.select :color, [%w(Azul primary),
                                %w(Vermelho danger),
                                %w(Cinza secondary),
                                %w(Verde success),
                                %w(Amarelho warning),
                                %w(Branco light),
                                %w(Preto dark)],
    {},{class: "form-control"}
    %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :user_id %>
    <%#= form.text_field :user_id %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit 'Criar Board', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="container-fluid">
  <h1>Editing Board</h1>

  <%= render 'form', board: @board %>

  <%#= link_to 'Show', @board %>
  <%= link_to 'Back', boards_path %>
</div>

app/views/boards/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 text-right">
      <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
    </div>
  </div>
  <div class="row center-element">
    <div class="col-md-12 col-sm-12 margin-top">
      <h2>Boards</h2>
      <%= link_to new_board_path  do %>
        <i class="fa fa-plus-circle fa-3x"></i>
      <% end %>
    </div>
    <div class="col-md-12 col-sm-12">
      Novo board
    </div>
    <div class="row" style="margin-top: 2rem;">

      <% if @boards.empty? %>
        <h5 class="center-element margin-top">Não há boards para exibir.</h5>
      <% else %>

        <% @boards.each do |board| %>
          <div class="col-md-3 col-sm-12">
            <div class="card <%= board.color != 'light' ? 'text-white-no-background' : ''%> bg-<%= board.color %> mb-3">
              <div class="card-header">
                <%= link_to board.nome, board_path(board), class: board.color != 'dark' ? 'text-dark' : 'text-white-no-background' %>
              </div>
              <div class="card-body">
                <!--        <h5 class="card-title">Primary card title</h5>-->
                <p class="card-text"><%= board.descricao %></p>
                <%= link_to board_path(board), method: :delete, data: {confirm: 'Deseja realmente excluir este board com todas suas etapas e tarefas?'} do %>
                  <i class="fa fa-trash customLink"></i>
                <% end %>
                <span>&nbsp;</span>
                <%= link_to edit_board_path(board) do %>
                  <i class="fa fa-edit customLink"></i>
                <% end %>
              </div>
              <!--        <div class="card-footer"><%#= %>></div>-->
            </div>
          </div>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container-fluid">
  <h3>Novo Board</h3>

  <%= render 'form', board: @board %>

  <%= link_to 'Voltar', boards_path, class: 'btn btn-light' %>
</div>

app/views/boards/show.html.erb
<div class="container-fluid margin-top">
  <div class="row center-element">
    <div style="margin-left: 2rem;">
      <%= link_to 'Voltar', boards_path %>
    </div>
    <div class="col-md-12">
      <h2><%= @board.nome %></h2>
      <%= link_to new_etapa_path  do %>
        <i class="fa fa-plus-circle fa-3x"></i>
      <% end %>
    </div>
    <div class="col-md-12">
      Nova etapa
    </div>
  </div>
  <% if @etapas %>
    <div class="row flex-nowrap" style="margin-top: 2rem;">
      <% @etapas.each_with_index do |etapa, i| %>
        <div class="col-md-3 center-element" style="background-color: <%= i % 2 == 0 ? 'lightgray;' : 'lightslategray;' %>">

          <%= link_to edit_etapa_path(etapa), class: 'customLink' do %>
            <h5><%= etapa.nome %></h5>
          <% end %>

          <% etapa.tasks.order('created_at ASC').each do |task| %>
            <div class="card border-dark" style="margin-bottom: 1rem;">
              <div class="card-header">
                <h6><%= task.nome %></h6>
              </div>
              <div class="card-body d-flex flex-column">
                <div>
                  <p><%= task.descricao %></p>
                </div>
                <div class="mt-auto" style="text-align: right;">

                  <%= link_to task_path(task), method: :delete, data: {confirm: 'Deseja realmente excluir esta tarefa?'} do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                  <span>&nbsp;</span>
                  <%= link_to edit_task_path(task) do %>
                    <i class="fa fa-edit"></i>
                  <% end %>

                  <!--                    <a href="#"><i class="fa-trash"></i></a>-->
                </div>
              </div>
            </div>
          <% end %>
          <%= link_to new_task_path(etapa: etapa.id) do %>
            <i class="fa fa-plus-circle"></i>
            <span>Nova tarefa</span>
          <% end %>
        </div>
      <% end %>
  <% else %>
    <div class="row center-element">
      <div class="col-md-12 col-sm-12">
        <div class="margin-top">
          <h4>Sem etapas para exibir</h4>
        </div>
      </div>
    </div>

  <% end %>
  </div>
</div>

app/views/etapas/_form.html.erb
<%= form_with(model: etapa, local: true) do |form| %>
  <% if etapa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(etapa.errors.count, "error") %> prohibited this etapa from being saved:</h2>

      <ul>
        <% etapa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :ordem %>
    <%= form.text_field :ordem, class: "form-control" %>
  </div>

  <div class="field d-none">
    <%= form.label :board_id %>
    <%= form.text_field :board_id, value: session[:user_board] %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar etapa', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/etapas/edit.html.erb
<div class="container-fluid">
  <h3>Editando etapa</h3>

  <%= render 'form', etapa: @etapa %>

  <!--  <%#= link_to 'Show', @etapa %> |-->
  <%= link_to 'Voltar', board_url(@etapa.board) %>
  |
  <%= link_to etapa_path(@etapa), method: :delete, data: {confirm: 'Isso deletará todas as tarefas atribuídas a esta etapa. Deseja continuar?'} do %>
    Deletar
  <% end %>
</div>

app/views/etapas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Etapas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @etapas.each do |etapa| %>
      <tr>
        <td><%= etapa.nome %></td>
        <td><%= etapa.board_id %></td>
        <td><%= link_to 'Show', etapa %></td>
        <td><%= link_to 'Edit', edit_etapa_path(etapa) %></td>
        <td><%= link_to 'Destroy', etapa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Etapa', new_etapa_path %>

app/views/etapas/new.html.erb
<div class="container-fluid">
  <h3>Nova Etapa</h3>

  <%= render 'form', etapa: @etapa %>

  <%= link_to 'Back', etapas_path %>

</div>

app/views/etapas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @etapa.nome %>
</p>

<p>
  <strong>Board:</strong>
  <%= @etapa.board_id %>
</p>

<%= link_to 'Edit', edit_etapa_path(@etapa) %> |
<%= link_to 'Back', etapas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloIbc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :javascript %>
  </body>
</html>

app/views/partials/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome%>
    <%= form.text_field :nome, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :descrição %>
    <%= form.text_area :descricao, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :etapa %>
    <%#= form.text_field :status, class: "form-control" %>
    <%= form.select :etapa_id, options_from_collection_for_select(@board.etapas, "id", "nome", task.etapa == nil ? @etapa.id : task.etapa.id), {}, {class: "form-control"} %>

  </div>

  <div class="actions">
    <%= form.submit 'Salvar task', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container-fluid">
  <h3>Editando Task</h3>
  <%= render 'form', task: @task %>

  <%= link_to 'Voltar', board_url(@task.etapa.board) %>

</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Status</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.nome %></td>
        <td><%= task.descricao %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<div class="container-fluid">
  <h3>Nova Task</h3>

  <%= render 'form', task: @task %>

  <%= link_to 'Back', board_path(@board) %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @task.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @task.descricao %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>